kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "py-oc"
spec:
  runPolicy: "Serial"
  tirggers:
    - 
      type: "GitHub"
      github:
        secret: "<>"
    - type: "Generic"
      generic:
        secret: "<>"
    - 
      type: "ImageChange"
  source:
    git:
      uri: "https://github.com/mrostamii/py-oc.git"
  strategy:
    type: Docker
    sourceStrategy:
      from:
        kind: "DockerImage"
        name: "ubuntu:16.04"
  output:
    to:
      kind: "ImageStreamTag"
      name: "py-oc:latest"